function [fitresult, gof] = M35(h35, b35)
%CREATEFIT(H35,B35)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : h35
%      Y Output: b35
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Aug-2022 17:03:45


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( h35, b35 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.0555247184332296;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'b35 vs. h35', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'h35', 'Interpreter', 'none' );
ylabel( 'b35', 'Interpreter', 'none' );
grid on


